apps/contacts/urls.py
from django.urls import path

from . import views

app_name = "contacts"

urlpatterns = [
    path("", views.show_contacts, name="show_contacts"),
    path(
        "<str:contact_id>/interactions/",
        views.show_contact_interactions,
        name="show_contact_interactions",
    ),
    path(
        "<str:contact_id>/departments/",
        views.show_contact_departments,
        name="show_contact_departments",
    ),
]

techsystem/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("opportunities/", include("apps.opportunities.urls")),
    path("contacts/", include("apps.contacts.urls")),
    path("contracts/", include("apps.contracts.urls")),
    path("leases/", include("apps.leases.urls")),
    path("auth/", include("apps.authentication.urls")),
    path("users/", include("apps.users.urls")),
]

apps/contacts/models.py
from django.db import models

# Create your models here.

apps/contacts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import CharField, Q, TextField
from django.shortcuts import render

from apps.common.services.pgadmin.models import Contact


@login_required
def show_contacts(request):
    query = request.GET.get("query")
    contacts_list = Contact.objects.order_by("contact_id")

    if query:
        fields = [
            field.name
            for field in Contact._meta.get_fields()
            if isinstance(field, (CharField, TextField))
        ]

        query_filter = Q()
        for field in fields:
            query_filter |= Q(**{f"{field}__icontains": query})

        contacts_list = contacts_list.filter(query_filter)

    paginator = Paginator(contacts_list, 10)
    page = request.GET.get("page")

    try:
        contacts = paginator.page(page)
    except PageNotAnInteger:
        contacts = paginator.page(1)
    except EmptyPage:
        contacts = paginator.page(paginator.num_pages)

    return render(request, "layouts/contacts.html", {"contacts": contacts})


@login_required
def show_contact_interactions(request, contact_id):
    contact = Contact.objects.get(contact_id=contact_id)
    interactions = contact.interaction_set.all()
    return render(
        request,
        "layouts/contact_interactions.html",
        {"contact": contact, "interactions": interactions},
    )


@login_required
def show_contact_departments(request, contact_id):
    contact = Contact.objects.get(contact_id=contact_id)
    departments = contact.contactdepartment_set.all()
    return render(
        request,
        "layouts/contact_departments.html",
        {"contact": contact, "departments": departments},
    )

apps/contacts/templates/layouts/contact_departments.html
{% extends "base.html" %}

{% block title %}
    Contact Departments
{% endblock title %}
{% block breadcrumb %}
    <div class="bg-[#dee7e7] p-4 rounded-lg shadow-md mb-4 w-full">
        <nav class="text-sm text-gray-600">
            <a href="{% url 'contacts:show_contacts' %}" class="hover:text-gray-800">Contacts</a> / <span>Interactions</span>
        </nav>
    </div>
{% endblock breadcrumb %}
{% block content %}
    <a href="{% url 'contacts:show_contacts' %}"
       class="inline-block mb-4 px-4 py-2 bg-gray-200 text-gray-700 rounded hover:bg-gray-300 transition duration-300">Back to Contacts</a>
    <h2 class="text-3xl font-bold mb-4">
        Contact Interactions for {{ contact.first_name }} {{ contact.last_name }}
    </h2>
    <table class="table">
        <thead>
            <tr>
                <th>Department ID</th>
                <th>Department Name</th>
                <th>Description</th>
                <th>Assignment Date</th>
            </tr>
        </thead>
        <tbody>
            {% for department in departments %}
                <tr>
                    <td>{{ department.department_id.department_id }}</td>
                    <td>{{ department.department_id.department_name }}</td>
                    <td>{{ department.department_id.description }}</td>
                    <td>{{ department.assignment_date }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

apps/contacts/templates/layouts/contact_interactions.html
{% extends "base.html" %}

{% block title %}
    Contact Interactions
{% endblock title %}
{% block breadcrumb %}
    <div class="bg-[#dee7e7] p-4 rounded-lg shadow-md mb-4 w-full">
        <nav class="text-sm text-gray-600">
            <a href="{% url 'contacts:show_contacts' %}" class="hover:text-gray-800">Contacts</a> / <span>Interactions</span>
        </nav>
    </div>
{% endblock breadcrumb %}
{% block content %}
    <a href="{% url 'contacts:show_contacts' %}"
       class="inline-block mb-4 px-4 py-2 bg-gray-200 text-gray-700 rounded hover:bg-gray-300 transition duration-300">Back to Contacts</a>
    <h2 class="text-3xl font-bold mb-4">
        Contact Interactions for {{ contact.first_name }} {{ contact.last_name }}
    </h2>
    <table class="table">
        <thead>
            <tr>
                <th>Interaction ID</th>
                <th>Interaction Date</th>
                <th>Interaction Type</th>
                <th>Notes</th>
            </tr>
        </thead>
        <tbody>
            {% for interaction in interactions %}
                <tr>
                    <td>{{ interaction.interaction_id }}</td>
                    <td>{{ interaction.interaction_date }}</td>
                    <td>{{ interaction.interaction_type }}</td>
                    <td>{{ interaction.notes }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

apps/contacts/templates/layouts/contacts.html
{% extends "base.html" %}

{% block title %}
    Contacts
{% endblock title %}

{% block breadcrumb %}
    <div class="bg-[#dee7e7] p-4 rounded-lg shadow-md mb-4 w-full">
        <nav class="text-sm text-gray-600">
            <a href="{% url 'index' %}" class="hover:text-gray-800">Home</a> / <span>Contacts</span>
        </nav>
    </div>
{% endblock breadcrumb %}

{% block content %}
    <div class="bg-white p-6 rounded-lg shadow-md">
        <h2 class="text-2xl font-bold mb-4">Contacts</h2>
        <form method="get" action="{% url 'contacts:show_contacts' %}" class="my-4 flex">
            <input type="text" name="query" id="search-bar" class="form-control border border-gray-300 rounded-l-lg p-2 flex-grow" placeholder="Search contacts">
            <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-r-lg border border-gray-300">Search</button>
        </form>
        <div class="overflow-x-auto">
            <table class="table" id="contacts-table">
                <thead>
                    <tr>
                        <th>Contact ID</th>
                        <th>Company NIT</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Position</th>
                        <th>Phone</th>
                        <th>Email</th>
                        <th>Last Interaction Date</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% if contacts %}
                        {% for contact in contacts %}
                            <tr>
                                <td>{{ contact.contact_id }}</td>
                                <td>{{ contact.nit.nit }}</td>
                                <td>{{ contact.first_name }}</td>
                                <td>{{ contact.last_name }}</td>
                                <td>{{ contact.position }}</td>
                                <td>{{ contact.phone }}</td>
                                <td>{{ contact.email }}</td>
                                <td>{{ contact.last_interaction_date }}</td>
                                <td>
                                    <div class="table-actions">
                                        <a href="{% url 'contacts:show_contact_interactions' contact.contact_id %}">Show Interactions</a>
                                        <a href="{% url 'contacts:show_contact_departments' contact.contact_id %}">Show Departments</a>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td colspan="9" class="text-center">No contacts found.</td>
                        </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
        
        <!-- Controles de paginación -->
        <div class="pagination mt-4">
            <nav>
                <ul class="flex justify-center space-x-2">
                    {% if contacts.has_previous %}
                        <li>
                            <a href="?page=1" class="px-3 py-2 border rounded bg-gray-200 hover:bg-gray-300">First</a>
                        </li>
                        <li>
                            <a href="?page={{ contacts.previous_page_number }}" class="px-3 py-2 border rounded bg-gray-200 hover:bg-gray-300">Previous</a>
                        </li>
                    {% endif %}
        
                    {% for num in contacts.paginator.page_range %}
                        {% if num == contacts.number %}
                            <li>
                                <span class="px-3 py-2 border rounded bg-blue-500 text-white">{{ num }}</span>
                            </li>
                        {% else %}
                            <li>
                                <a href="?page={{ num }}" class="px-3 py-2 border rounded bg-gray-200 hover:bg-gray-300">{{ num }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
        
                    {% if contacts.has_next %}
                        <li>
                            <a href="?page={{ contacts.next_page_number }}" class="px-3 py-2 border rounded bg-gray-200 hover:bg-gray-300">Next</a>
                        </li>
                        <li>
                            <a href="?page={{ contacts.paginator.num_pages }}" class="px-3 py-2 border rounded bg-gray-200 hover:bg-gray-300">Last</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div>        
    </div>
{% endblock content %}