apps/leases/urls.py
from django.urls import path

from . import views

app_name = "leases"

urlpatterns = [
    path("", views.show_leases, name="show_leases"),
    path("add-lease-request/", views.add_lease_request, name="add_lease_request"),
    path(
        "<str:lease_id>/edit-specific-attributes/",
        views.edit_specific_attributes,
        name="edit_specific_attributes",
    ),
    path(
        "leases/<str:lease_id>/save-specific-attributes/",
        views.save_specific_attributes,
        name="save_specific_attributes",
    ),
    path(
        "<str:lease_id>/products/",
        views.show_lease_products,
        name="show_lease_products",
    ),
    path("<str:lease_id>/edit-lease/", views.edit_lease, name="edit_lease"),
    path("<str:lease_id>/save-edit/", views.save_edit_lease, name="save_edit_lease"),
]

techsystem/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("opportunities/", include("apps.opportunities.urls")),
    path("contacts/", include("apps.contacts.urls")),
    path("contracts/", include("apps.contracts.urls")),
    path("leases/", include("apps.leases.urls")),
    path("auth/", include("apps.authentication.urls")),
    path("users/", include("apps.users.urls")),
]

apps/leases/models.py
from django.db import models

# Create your models here.

apps/leases/forms.py
from django import forms


class LeaseRequestForm(forms.Form):
    notes = forms.CharField(
        label="Additional Notes",
        required=False,
        widget=forms.Textarea(attrs={"class": "form-control", "rows": 4}),
    )

apps/leases/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.forms.models import model_to_dict
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from apps.common.services.mongodb.models import (
    Products,
    RentalRequests,
    RequestedEquipments,
    SpecificAttributes,
)
from apps.common.services.pgadmin.models import Category, CategorySpecificAttribute
from apps.leases.forms import LeaseRequestForm
from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
@login_required
def show_leases(request):
    user_company_nit = request.user.nit.nit
    leases_list = RentalRequests.objects.filter(customer_nit=user_company_nit)

    # Search functionality
    search_query = request.GET.get("search", "")
    if search_query:
        leases_list = leases_list.filter(customer_nit__icontains=search_query)

    # Pagination
    paginator = Paginator(leases_list, 10)
    page = request.GET.get("page")
    try:
        leases = paginator.page(page)
    except PageNotAnInteger:
        leases = paginator.page(1)
    except EmptyPage:
        leases = paginator.page(paginator.num_pages)

    return render(
        request, "layouts/leases.html", {"leases": leases, "search_query": search_query}
    )


@csrf_exempt
@login_required
def add_lease_request(request):
    if request.method == "POST":
        additional_notes = request.POST.get("additional_notes", "")
        requested_equipments = []

        # Process each product in the POST request
        for key, value in request.POST.items():
            if key.startswith("product-") and int(value) > 0:
                product_id = key.split("-")[1]
                quantity = int(value)
                requested_equipments.append(
                    RequestedEquipments(product_id=product_id, quantity=quantity)
                )

        # Create a new rental request
        rental_request = RentalRequests(
            customer_nit=request.user.nit.nit,
            requested_equipment=requested_equipments,
            status="pending",
        )
        rental_request.save()

        return redirect("leases:show_leases")
    else:
        form = LeaseRequestForm()

    products = Products.objects.all()
    products_list = []
    categories_list = [category.category_name for category in Category.objects.all()]
    for product in products:
        if product:
            product_dict = product.to_mongo().to_dict()
            if int(product_dict.get("common_attributes", {}).get("stock", 0)) > 0:
                product_dict["id"] = str(product.id)
                category_id = product_dict.get("category")
                category_name = Category.objects.get(
                    category_id=category_id
                ).category_name
                product_dict["category"] = category_name
                products_list.append(product_dict)
            else:
                print(
                    f"Product {product_dict.get('common_attributes', {}).get('brand', '')} {product_dict.get('common_attributes', {}).get('model', '')} out of stock"
                )
        else:
            print("Product not found")

    return render(
        request,
        "layouts/add_lease_request.html",
        {"form": form, "products": products_list, "categories": categories_list},
    )


@login_required
def edit_specific_attributes(request, lease_id):
    try:
        product = Products.objects.get(id=lease_id)
        specific_attributes = product.specific_attributes

        # Convert specific_attributes to a dictionary if necessary
        if hasattr(specific_attributes, "to_mongo"):
            specific_attributes = specific_attributes.to_mongo().to_dict()
        else:
            specific_attributes = vars(specific_attributes)

        # Get the fields of the SpecificAttributes model
        available_fields = SpecificAttributes._fields.keys()
        # Filter the fields that are already present in specific_attributes
        available_fields = [
            field for field in available_fields if field not in specific_attributes
        ]

        # Filter the fields that are already present in specific_attributes

        # Filter available fields based on the product category
        category_specific_attributes = CategorySpecificAttribute.objects.filter(
            category_id_id=product.category
        ).values_list("attribute_id__attribute_name", flat=True)
        available_fields = [
            field for field in available_fields if field in category_specific_attributes
        ]

    except Products.DoesNotExist:
        return redirect("leases:show_leases")

    return render(
        request,
        "layouts/edit_specific_attribute.html",
        {
            "lease_id": lease_id,
            "specific_attributes": specific_attributes,
            "available_fields": available_fields,
            "next": request.GET.get("next", "/"),
        },
    )


@csrf_exempt
@login_required
def save_specific_attributes(request, lease_id):
    if request.method == "POST":
        specific_attributes = request.POST.getlist("specific_attributes[]")
        product = Products.objects.get(id=lease_id)

        # Crear una instancia de SpecificAttributes
        specific_attributes_dict = {
            key: value
            for key, value in zip(specific_attributes[::2], specific_attributes[1::2])
        }
        specific_attributes_instance = SpecificAttributes(**specific_attributes_dict)

        product.specific_attributes = specific_attributes_instance
        product.save()

        return redirect("leases:add_lease_request")
    else:
        return render(
            request, "layouts/edit_specific_attribute.html", {"lease_id": lease_id}
        )


@login_required
def show_lease_products(request, lease_id):
    lease = RentalRequests.objects.get(id=lease_id)
    products_details = []
    for item in lease.requested_equipment:
        product = Products.objects.get(id=item.product_id)
        product_dict = product.to_mongo().to_dict()
        product_dict["quantity"] = item.quantity
        products_details.append(product_dict)
    return render(
        request,
        "layouts/lease_products.html",
        {"lease": lease, "products": products_details},
    )


@csrf_exempt
@login_required
def edit_lease(request, lease_id):
    product = Products.objects.get(id=lease_id)
    general_attributes = product.common_attributes

    if request.method == "POST":
        for key in general_attributes.keys():
            general_attributes[key] = request.POST.get(key, "N/A")
        product.common_attributes = general_attributes
        product.save()
        return redirect("leases:show_leases")

    return render(
        request,
        "layouts/edit_lease.html",
        {"lease_id": lease_id, "general_attributes": general_attributes},
    )


@login_required
def save_edit_lease(request, lease_id):
    lease = get_object_or_404(RentalRequests, id=lease_id)
    form = LeaseRequestForm(request.POST, instance=lease)

    if form.is_valid():
        form.save()
        return redirect("show_leases")

    return render(request, "layouts/edit_lease.html", {"form": form, "lease": lease})

apps/leases/templates/layouts/add_lease_request.html
{% extends "base.html" %}

{% block title %}
    Add Lease Request
{% endblock title %}
{% block breadcrumb %}
    <div class="bg-gray-200 p-4 rounded-lg shadow-md mb-4 w-full">
        <nav class="text-sm text-gray-600">
            <a href="{% url 'index' %}" class="hover:text-gray-800">Home</a> / <a href="{% url 'leases:show_leases' %}" class="hover:text-gray-800">Leases</a> / <span>Add Lease Request</span>
        </nav>
    </div>
{% endblock breadcrumb %}
{% block content %}
    <h2 class="text-xl font-bold mb-4">Available Products</h2>
    <div class="container mx-auto my-4 space-y-4">
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <input type="text"
                   id="search-bar"
                   class="border border-gray-300 rounded-lg p-2 focus:ring focus:ring-blue-300 w-full"
                   placeholder="Search by product name or brand" />
            <select id="category-filter"
                    class="border border-gray-300 rounded-lg p-2 focus:ring focus:ring-blue-300 w-full">
                <option value="">All Categories</option>
                {% for category in categories %}
                    <option value="{{ category }}">{{ category }}</option>
                {% endfor %}
            </select>
        </div>
        <form method="post"  id="lease-request-form">
            {% csrf_token %}
            <div class="grid grid-cols-1 md:grid-cols-4 gap-6">
                {% csrf_token %}
                {% for product in products %}
                    <div class="bg-white shadow-lg rounded-lg flex flex-col h-full border border-gray-200">
                        <div class="overflow-hidden h-44 flex justify-center items-center p-1">
                            <img src="{{ product.image_url }}"
                                 alt="{{ product.common_attributes.brand }} {{ product.common_attributes.model }}"
                                 class="object-contain h-full w-full"
                                 width="100"
                                 height="100" />
                        </div>
                        <div class="p-4 flex flex-col flex-grow">
                            <h5 class="text-lg font-semibold">
                                {{ product.common_attributes.brand }} {{ product.common_attributes.model }}
                            </h5>
                            <p class="text-sm text-gray-700 mb-4">
                                <strong>Category:</strong> {{ product.category }}
                                <br />
                                <strong>Price:</strong> ${{ product.common_attributes.price }}
                                <br />
                                <strong>Stock:</strong> {{ product.common_attributes.stock }}
                                <br />
                                <strong>Warranty:</strong> {{ product.common_attributes.warranty_period }}
                                <br />
                                <h5>Specific Attributes:</h5>
                                <ul class="list-disc list-inside">
                                    {% for key, value in product.specific_attributes.items %}
                                        <li>
                                            <strong>{{ key|capfirst }}:</strong> {{ value }}
                                        </li>
                                    {% endfor %}
                                </ul>
                                <div class="mt-4"></div>
                            </p>
                            {% if request.user.is_staff %}
                                <div class="mt-auto mb-4 flex flex-col items-center space-y-2">
                                    <a href="{% url 'leases:edit_lease' lease_id=product.id|stringformat:'s' %}"
                                       class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                                        Edit general attributes
                                    </a>
                                    <a href="{% url 'leases:edit_specific_attributes' lease_id=product.id|stringformat:'s' %}"
                                       class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                                        Edit specific attributes
                                    </a>
                                </div>
                            {% endif %}
                            <div class="flex justify-center items-center">
                                <button type="button"
                                        class="border border-gray-300 rounded-l-lg w-10 h-10 bg-gray-200 hover:bg-gray-300"
                                        onclick="decreaseQuantity(this)">-</button>
                                <input type="number"
                                       name="product-{{ product.id }}"
                                       value="0"
                                       min="0"
                                       max="{{ product.common_attributes.stock }}"
                                       class="w-16 h-10 text-center border-t border-b border-gray-300" />
                                <button type="button"
                                        class="border border-gray-300 rounded-r-lg w-10 h-10 bg-gray-200 hover:bg-gray-300"
                                        onclick="increaseQuantity(this)">+</button>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div id="selected-products-container"></div>
            <div class="mt-4">
                <label for="additional-notes"
                       class="block text-lg font-family text-gray-700">
                    Additional Notes:
                </label>
                <textarea id="additional-notes"
                          name="additional_notes"
                          rows="4"
                          class="mt-1 block w-full border border-gray-300 rounded-md shadow-sm focus:ring focus:ring-blue-300"></textarea>
            </div>
            <button type="submit"
                    class="bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-4">
                Submit Request
            </button>
        </form>
    </div>
    <script>
        function decreaseQuantity(button) {
            const container = button.closest('div');
            const input = container.querySelector('input[type="number"]');
            const value = parseInt(input.value);
            if (value > parseInt(input.min)) {
                input.value = value - 1;
            }
        }

        function increaseQuantity(button) {
            const container = button.closest('div');
            const input = container.querySelector('input[type="number"]');
            const value = parseInt(input.value);
            const max = parseInt(input.max);
            if (value < max) {
                input.value = value + 1;
            }
        }

        document.addEventListener('DOMContentLoaded', () => {
            const searchBar = document.getElementById('search-bar');
            const categoryFilter = document.getElementById('category-filter');
            const productCards = document.querySelectorAll('.grid > div');

            function filterProducts() {
                const searchTerm = searchBar.value.toLowerCase();
                const selectedCategory = categoryFilter.value.toLowerCase();

                productCards.forEach(card => {
                    const title = card.querySelector('h5').textContent.toLowerCase();
                    const category = card.querySelector('p').textContent.toLowerCase();

                    const matchesSearch = title.includes(searchTerm);
                    const matchesCategory = selectedCategory === '' || category.includes(selectedCategory);

                    card.style.display = matchesSearch && matchesCategory ? '' : 'none';
                });
            }

            searchBar.addEventListener('input', filterProducts);
            categoryFilter.addEventListener('change', filterProducts);
        });
    </script>
{% endblock content %}

apps/leases/templates/layouts/edit_lease.html
{% extends "base.html" %}

{% block title %}
  Edit General Attributes
{% endblock title %}
{% block breadcrumb %}
  <div class="bg-gray-200 p-4 rounded-lg shadow-md mb-4 w-full">
    <nav class="text-sm text-gray-600">
      <a href="{% url 'index' %}" class="hover:text-gray-800">Home</a> / <span>Leases</span> / <span>Edit General Attributes</span>
    </nav>
  </div>
{% endblock breadcrumb %}
{% block content %}
  <div class="bg-white p-6 rounded-lg shadow-md">
    <h2 class="text-3xl font-bold mb-4">Edit General Attributes</h2>
    <form method="post" action="{% url 'leases:edit_lease' lease_id %}">
      {% csrf_token %}
      <div id="attributes-container">
        {% for key, value in general_attributes.items %}
          <div class="attribute-item mb-4">
            <label for="{{ key }}" class="block text-sm font-medium text-gray-700">
              {{ key|capfirst }}
            </label>
            <input type="input"
                   name="{{ key }}"
                   value="{{ value }}"
                   class="custom-input shadow appearance-none border rounded w-full py-2 px-3 text-gray-900 bg-white leading-tight focus:outline-none focus:shadow-outline placeholder-gray-500"
                   placeholder="Enter value or N/A" />
          </div>
        {% endfor %}
      </div>
      <button type="submit"
              class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-4">
        Save
      </button>
    </form>
  </div>
  <style>
    .custom-input {
        border: 1px solid #ccc;
        padding: 10px;
        background-color: #f9f9f9;
        color: #333;
    }
    .custom-input:focus {
        outline: none;
        box-shadow: 0 0 5px rgba(81, 203, 238, 1);
        border: 1px solid rgba(81, 203, 238, 1);
        background-color: #f9f9f9;
        border-radius: 0;
    }
  </style>
{% endblock content %}

apps/leases/templates/layouts/edit_specific_attribute.html
{% extends "base.html" %}

{% block title %}
  Edit Specific Attributes
{% endblock title %}
{% block breadcrumb %}
  <div class="bg-gray-200 p-4 rounded-lg shadow-md mb-4 w-full">
    <nav class="text-sm text-gray-600">
      <a href="{% url 'index' %}" class="hover:text-gray-800">Home</a> / <span>Leases</span> / <span>Add Lease Request</span> / <span>Edit specific attributes</span>
    </nav>
  </div>
{% endblock breadcrumb %}
{% block content %}
  <style>
    .placeholder-gray-500::placeholder {
      color: #6b7280; 
    }
  </style>
  <div class="bg-white p-6 rounded-lg shadow-md">
    <h2 class="text-3xl font-bold mb-4">Edit Specific Attributes</h2>
    <form method="post"
          action="{% url 'leases:save_specific_attributes' lease_id %}">
      {% csrf_token %}
      <div id="attributes-container">
        {% for key, value in specific_attributes.items %}
          <div class="attribute-item mb-4">
            <input type="input"
                   name="specific_attributes[]"
                   value="{{ key }}"
                   class="custom-input shadow appearance-none border rounded w-full py-2 px-3 text-gray-900 bg-white leading-tight focus:outline-none focus:shadow-outline placeholder-gray-500"
                   placeholder="Attribute Name"
                   readonly />
            <input type="input"
                   name="specific_attributes[]"
                   value="{{ value }}"
                   class="custom-input shadow appearance-none border rounded w-full py-2 px-3 text-gray-900 bg-white leading-tight focus:outline-none focus:shadow-outline placeholder-gray-500"
                   placeholder="Attribute Value" />
            <button type="button"
                    class="remove-attribute bg-red-500 hover:bg-red-700 text-white font-bold py-1 px-2 rounded mt-2">
              Remove
            </button>
          </div>
        {% endfor %}
      </div>
      <div class="mb-4">
        <select id="attribute-type"
                class="form-control block w-full px-3 py-2 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
          <option value="" class="text-gray-500">Select Attribute Type</option>
          {% for field in available_fields %}
            <option value="{{ field }}" class="text-gray-900">{{ field|capfirst }}</option>
          {% endfor %}
        </select>
      </div>
      <button type="button"
              id="add-attribute"
              class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">
        Add Attribute
      </button>
      <button type="submit"
              class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-4">
        Save
      </button>
    </form>
  </div>
  <style>
    .custom-input {
        /* Sobrescribe los estilos aquí */
        border: 1px solid #ccc;
        padding: 10px;
        background-color: #f9f9f9;
        color: #333;
    }
    .custom-input:focus {
        outline: none;
        box-shadow: 0 0 5px rgba(81, 203, 238, 1);
        border: 1px solid rgba(81, 203, 238, 1);
        background-color: #f9f9f9; /* Sobrescribe el color de fondo */
        border-radius: 0; /* Sobrescribe el border-radius */
    }
  </style>
  <script>
      document.getElementById('add-attribute').addEventListener('click', function() {
          var attributeType = document.getElementById('attribute-type').value;
          if (attributeType) {
              var container = document.getElementById('attributes-container');
              var div = document.createElement('div');
              div.className = 'attribute-item mb-4';
              div.innerHTML = `
                  <input type="text" name="specific_attributes[]" value="${attributeType}" class="custom-input shadow appearance-none border rounded w-full py-2 px-3 text-gray-900 bg-white leading-tight focus:outline-none focus:shadow-outline placeholder-gray-500" placeholder="Attribute Name" readonly />
                  <input type="text" name="specific_attributes[]" value="" class="custom-input shadow appearance-none border rounded w-full py-2 px-3 text-gray-900 bg-white leading-tight focus:outline-none focus:shadow-outline placeholder-gray-500" placeholder="Attribute Value" />
                  <button type="button" class="remove-attribute bg-red-500 hover:bg-red-700 text-white font-bold py-1 px-2 rounded mt-2">Remove</button>
              `;
              container.appendChild(div);

              // Remove the selected option from the dropdown
              var select = document.getElementById('attribute-type');
              select.querySelector(`option[value="${attributeType}"]`).remove();
          }
      });

      document.addEventListener('click', function(e) {
          if (e.target && e.target.classList.contains('remove-attribute')) {
              var attributeName = e.target.previousElementSibling.previousElementSibling.value;
              var select = document.getElementById('attribute-type');

              // Add the removed attribute back to the dropdown
              var option = document.createElement('option');
              option.value = attributeName;
              option.text = attributeName.charAt(0).toUpperCase() + attributeName.slice(1);
              select.appendChild(option);

              e.target.parentElement.remove();
          }
      });
  </script>
{% endblock content %}

apps/leases/templates/layouts/lease_products.html
{% extends "base.html" %}

{% block title %}
    Lease Products
{% endblock title %}
{% block breadcrumb %}
    <div class="bg-[#dee7e7] p-4 rounded-lg shadow-md mb-4 w-full">
        <nav class="text-sm text-gray-600">
            <a href="{% url 'index' %}" class="hover:text-gray-800">Home</a> / <a href="{% url 'leases:show_leases' %}" class="hover:text-gray-800">Leases</a> / <span>Lease Products</span>
        </nav>
    </div>
{% endblock breadcrumb %}
{% block content %}
    <a href="{% url 'leases:show_leases' %}"
       class="inline-block mb-4 px-4 py-2 bg-gray-200 text-gray-700 rounded hover:bg-gray-300 transition duration-300">Back to Leases</a>
    <h2 class="text-2xl font-bold mb-4">Lease Products</h2>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {% for product in products %}
            <div class="bg-white shadow-md rounded-lg overflow-hidden">
                <img src="{{ product.image_url }}"
                     alt="{{ product.common_attributes.brand }} {{ product.common_attributes.model }}"
                     class="w-full h-48 object-contain"
                     width="300"
                     height="200" />
                <div class="p-4">
                    <h3 class="text-lg font-semibold">
                        {{ product.common_attributes.brand }} {{ product.common_attributes.model }}
                    </h3>
                    <p class="text-gray-600">Category: {{ product.category }}</p>
                    <p class="text-gray-600">Price: ${{ product.common_attributes.price }}</p>
                    <p class="text-gray-600">Quantity: {{ product.quantity }}</p>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

apps/leases/templates/layouts/leases.html
{% extends "base.html" %}

{% block title %}
    Leases
{% endblock title %}
{% block breadcrumb %}
    <div class="bg-[#dee7e7] p-4 rounded-lg shadow-md mb-4 w-full">
        <nav class="text-sm text-gray-600">
            <a href="{% url 'index' %}" class="hover:text-gray-800">Home</a> / <span>Leases</span>
        </nav>
    </div>
{% endblock breadcrumb %}
{% block content %}
    <style>
        .right-button {
            display: flex;
            justify-content: flex-end;
            align-items: flex-end;
            height: 100%;
        }
    </style>
    <div class="flex justify-between items-center mb-4">
        <h2 class="text-2xl font-bold">Leases</h2>
        <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
                onclick="window.location.href='/leases/add-lease-request/'">
            Add Lease
        </button>
    </div>
    <div class="my-4">
        <form method="get"
              action="{% url 'leases:show_leases' %}"
              class="my-4 flex">
            <input type="text"
                   name="query"
                   id="search-bar"
                   class="form-control border border-gray-300 rounded-l-lg p-2 flex-grow"
                   placeholder="Search leases" />
            <button type="submit"
                    class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-r-lg border border-gray-300">
                Search
            </button>
        </form>
    </div>
    <table class="table" id="leases-table">
        <thead>
            <tr>
                <th>Customer NIT</th>
                <th>Request Date (UTC)</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for lease in leases %}
                <tr>
                    <td>{{ lease.customer_nit }}</td>
                    <td>{{ lease.request_date }}</td>
                    <td>
                        <span class="badge {% if lease.status == 'pending' %}badge-secondary {% elif lease.status == 'approved' %}badge-success {% elif lease.status == 'rejected' %}badge-danger {% endif %}">
                            {{ lease.status }}
                        </span>
                    </td>
                    <td>
                        <div class="table-actions">
                            <a href="{% url 'leases:show_lease_products' lease.id %}">Show Products</a>
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <!-- Pagination controls -->
    <div class="pagination mt-4">
        <nav>
            <ul class="flex justify-center space-x-2">
                {% if leases.has_previous %}
                    <li>
                        <a href="?page=1&search={{ search_query }}"
                           class="px-3 py-2 border rounded bg-gray-200 hover:bg-gray-300">First</a>
                    </li>
                    <li>
                        <a href="?page={{ leases.previous_page_number }}&search={{ search_query }}"
                           class="px-3 py-2 border rounded bg-gray-200 hover:bg-gray-300">Previous</a>
                    </li>
                {% endif %}
                {% for num in leases.paginator.page_range %}
                    {% if num == leases.number %}
                        <li>
                            <span class="px-3 py-2 border rounded bg-blue-500 text-white">{{ num }}</span>
                        </li>
                    {% else %}
                        <li>
                            <a href="?page={{ num }}&search={{ search_query }}"
                               class="px-3 py-2 border rounded bg-gray-200 hover:bg-gray-300">{{ num }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
                {% if leases.has_next %}
                    <li>
                        <a href="?page={{ leases.next_page_number }}&search={{ search_query }}"
                           class="px-3 py-2 border rounded bg-gray-200 hover:bg-gray-300">Next</a>
                    </li>
                    <li>
                        <a href="?page={{ leases.paginator.num_pages }}&search={{ search_query }}"
                           class="px-3 py-2 border rounded bg-gray-200 hover:bg-gray-300">Last</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
{% endblock content %}