apps/contacts/urls.py
from django.urls import path

from . import views

app_name = "contacts"

urlpatterns = [
    path("", views.show_contacts, name="show_contacts"),
    path(
        "<str:contact_id>/interactions/",
        views.show_contact_interactions,
        name="show_contact_interactions",
    ),
    path(
        "<str:contact_id>/departments/",
        views.show_contact_departments,
        name="show_contact_departments",
    ),
]

apps/contracts/urls.py
from django.urls import path

from . import views

app_name = "contracts"

urlpatterns = [
    path("", views.show_contracts, name="show_contracts"),
    path(
        "<str:contract_id>/delivery_certificates/",
        views.show_delivery_certificates,
        name="show_delivery_certificates",
    ),
    path(
        "<str:certificate_id>/equipments/",
        views.show_equipments,
        name="show_equipments",
    ),
]

apps/leases/urls.py
from django.urls import path

from . import views

app_name = "leases"

urlpatterns = [
    path("", views.show_leases, name="show_leases"),
    path("add-lease-request/", views.add_lease_request, name="add_lease_request"),
    path(
        "<str:lease_id>/edit-specific-attributes/",
        views.edit_specific_attributes,
        name="edit_specific_attributes",
    ),
    path(
        "leases/<str:lease_id>/save-specific-attributes/",
        views.save_specific_attributes,
        name="save_specific_attributes",
    ),
    path(
        "<str:lease_id>/products/",
        views.show_lease_products,
        name="show_lease_products",
    ),
    path("<str:lease_id>/edit-lease/", views.edit_lease, name="edit_lease"),
    path("<str:lease_id>/save-edit/", views.save_edit_lease, name="save_edit_lease"),
]

apps/users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("", views.show_users, name="show_users"),
    path(
        "company-details/",
        views.show_user_company_details,
        name="show_user_company_details",
    ),
]

techsystem/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("opportunities/", include("apps.opportunities.urls")),
    path("contacts/", include("apps.contacts.urls")),
    path("contracts/", include("apps.contracts.urls")),
    path("leases/", include("apps.leases.urls")),
    path("auth/", include("apps.authentication.urls")),
    path("users/", include("apps.users.urls")),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta
      name="description"
      content="TechSystem is your go-to platform for tech solutions."
    />
    <meta
      name="keywords"
      content="TechSystem, technology, solutions, platform"
    />
    <title>
      {% block title %}
      {% endblock title %}
    </title>
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
    <link rel="stylesheet" href="{% static 'src/output.css' %}" />
    <link rel="stylesheet" href="{% static 'src/styles.css' %}" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap" />
    <style>
      body {
        font-family: 'Inter', sans-serif;
      }
    </style>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
    />
  </head>
  <body class="min-h-screen flex flex-col bg-blue-50 text-gray-700">
    <header class="bg-blue-600 text-white shadow-lg sticky top-0 z-50">
      <nav class="container mx-auto flex justify-between items-center p-4">
        <a
          href="{% url 'index' %}"
          class="text-2xl font-bold hover:text-blue-300 transition"
        >
          TechSystem
        </a>
        <ul class="flex space-x-4">
          {% if request.user.is_authenticated %}
          <li>
            <a
              href="{% url 'users:show_user_company_details' %}"
              class="hover:text-blue-300 transition"
            >
              My Company Details
            </a>
          </li>
          <li>
            <a
              href="{% url 'leases:show_leases' %}"
              class="hover:text-blue-300 transition"
            >
              Leases
            </a>
          </li>
          <li>
            <a
              href="{% url 'contacts:show_contacts' %}"
              class="hover:text-blue-300 transition"
            >
              Contacts
            </a>
          </li>
          <li>
            <a
              href="{% url 'contracts:show_contracts' %}"
              class="hover:text-blue-300 transition"
            >
              Contracts
            </a>
          </li>
          {% if request.user.is_staff %}
          <li>
            <a
              href="{% url 'users:show_users' %}"
              class="hover:text-blue-300 transition"
            >
              Users
            </a>
          </li>
          {% endif %}
          <li>
            <a
              href="{% url 'opportunities:show_opportunities' %}"
              class="hover:text-blue-300 transition"
            >
              Opportunities
            </a>
          </li>
          {% if request.user.is_staff %}
            <li>
              <a
                href="{% url 'admin:index' %}"
                class="hover:text-blue-300 transition"
              >
                Admin Panel
              </a>
            </li>
          {% endif %}
          <li>
            <a
              href="{% url 'authentication:logout' %}"
              class="hover:text-blue-300 transition"
            >
              Logout
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
    </header>
    <main class="flex-grow container mx-auto p-6">
      {% if request.user.is_authenticated %}
      {% block breadcrumb %}
      {% endblock breadcrumb %}
      {% endif %}
      <div class="bg-white p-6 rounded-lg shadow-lg">
        {% block content %}
        {% endblock content %}
      </div>
    </main>
    <footer class="bg-blue-600 text-white text-center py-4">
      <p>© 2024 TechSystem. All rights reserved.</p>
    </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/alpinejs/3.12.1/cdn.min.js"></script>
  </body>
</html>

templates/index.html
{% extends "base.html" %}

{% load static %}

{% block title %}
    Home
{% endblock title %}
{% block breadcrumb %}
    <div class="bg-[#dee7e7] p-4 rounded-lg shadow-md mb-4 w-full">
        <nav class="text-sm text-gray-600">
            <a href="{% url 'index' %}" class="hover:text-gray-800">Home</a>
        </nav>
    </div>
{% endblock breadcrumb %}
{% block content %}
    {% if request.user.is_authenticated %}
        <div class="bg-gray-300 p-6 rounded-lg shadow-md">
            <h2 class="text-2xl font-bold mb-4">Welcome to TechSystem</h2>
            <p class="text-lg mb-6">Your go-to platform for managing contracts efficiently.</p>
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                <!-- Accesos Rápidos -->
                <div class="bg-gray-100 p-4 rounded-lg shadow-md">
                    <h3 class="text-xl font-semibold mb-2">User Information</h3>
                    <ul class="space-y-2">
                        <li>
                            <strong>Username:</strong> {{ request.user.username }}
                        </li>
                        <li>
                            <strong>Last Login:</strong> {{ request.user.last_login|date:"F j, Y, g:i a" }}
                        </li>
                    </ul>
                </div>
                <!-- Estadísticas Relevantes -->
                <div class="bg-gray-100 p-4 rounded-lg shadow-md">
                    <h3 class="text-xl font-semibold mb-2">Statistics</h3>
                    <ul class="space-y-2">
                        <li>
                            Total Contracts: <span class="font-bold">{{ contracts_number }}</span>
                        </li>
                        <li>
                            Active Contracts: <span class="font-bold">{{ active_contracts_count }}</span>
                        </li>
                        <li>
                            Expired Contracts: <span class="font-bold">{{ expired_contracts_count }}</span>
                        </li>
                    </ul>
                </div>
                <!-- Último Contrato -->
                <div class="bg-gray-100 p-4 rounded-lg shadow-md">
                    <h3 class="text-xl font-semibold mb-2">Last Added Contract</h3>
                    <ul class="space-y-2">
                        {% if last_contract %}
                            <li class="border-b border-gray-300 pb-2 mb-2">
                                <strong>Contract ID:</strong> {{ last_contract.contract_id }}
                                <br />
                                <strong>NIT:</strong> {{ last_contract.nit }}
                                <br />
                                <strong>Start Date:</strong> {{ last_contract.start_date|date:"F j, Y" }}
                                <br />
                                <strong>End Date:</strong> {{ last_contract.end_date|date:"F j, Y" }}
                                <br />
                                <strong>Contract Number:</strong> {{ last_contract.contract_number }}
                            </li>
                        {% else %}
                            <li>No contracts found.</li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    {% else %}
        <div class="absolute inset-0 min-h-screen bg-cover bg-center w-full h-full"
             style="background-image: url('{% static 'images/laptop_at_night_laptop_3.jpg' %}')">
            <div class="relative flex flex-col items-start justify-center min-h-screen bg-gray-900 bg-opacity-50 text-white w-full h-full p-8">
                <h2 class="text-4xl font-bold mb-4">Welcome to TechSystem</h2>
                <p class="text-lg mb-6">Your go-to platform for tech solutions.</p>
                <a href="{% url 'authentication:login' %}?next={{ request.path }}"
                   class="relative inline-block px-4 py-2 text-white rounded-lg hover:text-faf0e6 backdrop-filter backdrop-blur-md"
                   style="background: linear-gradient(270deg, rgba(75, 85, 99, 0.5) 0%, rgba(75, 85, 99, 0) 100%)">
                    Login
                </a>
            </div>
        </div>
    {% endif %}
{% endblock content %}